$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: lightgbm
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
conda_file: ./conda-environment.yml
description: LightGBM environment created from a Docker image plus Conda environment for AML.